services:
  - type: web
    name: bovweight-ia
    runtime: python
    buildCommand: >
      pip install -r requirements.txt &&
      pip install "ultralytics==8.3.163" &&
      python export_model.py &&
      pip uninstall -y torch torchvision torchaudio ultralytics
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: YOLO_CONFIG_DIR
        value: "/tmp"
    plan: free
